/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as IpoIndexRouteImport } from './routes/ipo/index'
import { Route as AccountsIndexRouteImport } from './routes/accounts/index'
import { Route as IpoStatusRouteImport } from './routes/ipo/status'
import { Route as IpoResultsRouteImport } from './routes/ipo/results'
import { Route as IpoApplyRouteImport } from './routes/ipo/apply'
import { Route as AccountsNewRouteImport } from './routes/accounts/new'
import { Route as AccountsIdRouteImport } from './routes/accounts/$id'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const IpoIndexRoute = IpoIndexRouteImport.update({
  id: '/ipo/',
  path: '/ipo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const IpoStatusRoute = IpoStatusRouteImport.update({
  id: '/ipo/status',
  path: '/ipo/status',
  getParentRoute: () => rootRouteImport,
} as any)
const IpoResultsRoute = IpoResultsRouteImport.update({
  id: '/ipo/results',
  path: '/ipo/results',
  getParentRoute: () => rootRouteImport,
} as any)
const IpoApplyRoute = IpoApplyRouteImport.update({
  id: '/ipo/apply',
  path: '/ipo/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsNewRoute = AccountsNewRouteImport.update({
  id: '/accounts/new',
  path: '/accounts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/accounts/$id',
  path: '/accounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/accounts/new': typeof AccountsNewRoute
  '/ipo/apply': typeof IpoApplyRoute
  '/ipo/results': typeof IpoResultsRoute
  '/ipo/status': typeof IpoStatusRoute
  '/accounts/': typeof AccountsIndexRoute
  '/ipo/': typeof IpoIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/accounts/new': typeof AccountsNewRoute
  '/ipo/apply': typeof IpoApplyRoute
  '/ipo/results': typeof IpoResultsRoute
  '/ipo/status': typeof IpoStatusRoute
  '/accounts': typeof AccountsIndexRoute
  '/ipo': typeof IpoIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/accounts/$id': typeof AccountsIdRoute
  '/accounts/new': typeof AccountsNewRoute
  '/ipo/apply': typeof IpoApplyRoute
  '/ipo/results': typeof IpoResultsRoute
  '/ipo/status': typeof IpoStatusRoute
  '/accounts/': typeof AccountsIndexRoute
  '/ipo/': typeof IpoIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/accounts/$id'
    | '/accounts/new'
    | '/ipo/apply'
    | '/ipo/results'
    | '/ipo/status'
    | '/accounts/'
    | '/ipo/'
    | '/portfolio/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/accounts/$id'
    | '/accounts/new'
    | '/ipo/apply'
    | '/ipo/results'
    | '/ipo/status'
    | '/accounts'
    | '/ipo'
    | '/portfolio'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/accounts/$id'
    | '/accounts/new'
    | '/ipo/apply'
    | '/ipo/results'
    | '/ipo/status'
    | '/accounts/'
    | '/ipo/'
    | '/portfolio/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  AccountsIdRoute: typeof AccountsIdRoute
  AccountsNewRoute: typeof AccountsNewRoute
  IpoApplyRoute: typeof IpoApplyRoute
  IpoResultsRoute: typeof IpoResultsRoute
  IpoStatusRoute: typeof IpoStatusRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  IpoIndexRoute: typeof IpoIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipo/': {
      id: '/ipo/'
      path: '/ipo'
      fullPath: '/ipo/'
      preLoaderRoute: typeof IpoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipo/status': {
      id: '/ipo/status'
      path: '/ipo/status'
      fullPath: '/ipo/status'
      preLoaderRoute: typeof IpoStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipo/results': {
      id: '/ipo/results'
      path: '/ipo/results'
      fullPath: '/ipo/results'
      preLoaderRoute: typeof IpoResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipo/apply': {
      id: '/ipo/apply'
      path: '/ipo/apply'
      fullPath: '/ipo/apply'
      preLoaderRoute: typeof IpoApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/new': {
      id: '/accounts/new'
      path: '/accounts/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AccountsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  AccountsIdRoute: AccountsIdRoute,
  AccountsNewRoute: AccountsNewRoute,
  IpoApplyRoute: IpoApplyRoute,
  IpoResultsRoute: IpoResultsRoute,
  IpoStatusRoute: IpoStatusRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  IpoIndexRoute: IpoIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
